# Generated by Django 4.2.4 on 2023-12-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_group_lesson_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='day_of_Week',
            field=models.CharField(default='ПН', max_length=2),
            preserve_default=False,
        ),
    ]
