# Generated by Django 4.2.4 on 2023-12-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_lesson_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='ОРГ', max_length=100),
            preserve_default=False,
        ),
    ]
