# Generated by Django 4.2.4 on 2023-12-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(default='14:00', max_length=20),
            preserve_default=False,
        ),
    ]
