# Generated by Django 4.2.4 on 2023-12-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_lesson_end_time_alter_lesson_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subgroup',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ison', models.BooleanField()),
                ('date', models.CharField(max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
